# Generated by Django 4.0.4 on 2022-09-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_email_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
